---
title: "Data Analysis for Early and Late Lung-colonizing Tumors"
author: "Emily Franz"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output:
    html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    number_sections: false
    code_folding: hide
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    tidy = TRUE,
    echo = TRUE,
    cache = TRUE,
    collapse = TRUE,
    tidy.opts = list(width.cutoff = 95),
    message = FALSE,
    warning = FALSE,
    cache.lazy = FALSE
)
```

```{r lib}
# Load packages
library(Seurat)
library(tidyverse)
library(rrrSingleCellUtils)

# Set random generator seed to facilitate reproducibility
set.seed(888)

# set working directory 
setwd("/gpfs0/home2/gdrobertslab/lab/Analysis/Emily/MCL1_early_met_survival/")
```

# Load Datasets

Datasets are from tumors collected from mouse lungs at early (day 14 post injection of tumor cells) and late (day 35 post injection of tumor cells) timepoints. mCherry was used to label the tumor cells as well as the surrounding niche cells.

```{r load}
#### D14 ####
# Load mCherry+ cells (tumor and surrounding microenvironment cells) from lungs collected on day 14
d14_positive <- tenx_load_qc("/gpfs0/home2/gdrobertslab/lab/Counts/S0082/filtered_feature_bc_matrix",
                             species_pattern = "^hg19_")

# Subset for QC
d14_positive <- subset(d14_positive,
                       subset = nCount_RNA > 800 &
                         nCount_RNA < 11000 &
                         percent.mt < 20)

## Add labels to metadata
d14_positive$timepoint <- "Day 14"
d14_positive$group <- "Early"
d14_positive$selection <- "mCherry+"

#### D35 ####
# Load mCherry+ cells (tumor and surrounding microenvironment cells) from lungs collected on day 35
d35_positive <- tenx_load_qc("/gpfs0/home2/gdrobertslab/lab/Counts/S0084/filtered_feature_bc_matrix",
                             species_pattern = "^hg19_")

## Add labels to metadata
d35_positive$timepoint <- "Day 35"
d35_positive$group <- "Late"
d35_positive$selection <- "mCherry+"

#Subset for QC
d35_positive <- subset(d35_positive,
                       subset = nCount_RNA > 800 &
                         nCount_RNA < 40000 &
                         percent.mt < 20)

#### Mouse ####
#### D14 ####
# Load mCherry+ cells (tumor and surrounding microenvironment cells) from lungs collected on day 14
md14_positive <- tenx_load_qc("/gpfs0/home2/gdrobertslab/lab/Counts/S0082/filtered_feature_bc_matrix",
                              species_pattern = "^mm10_")

# Subset for QC
md14_positive <- subset(md14_positive,
                        subset = nCount_RNA > 800 &
                          nCount_RNA < 7000 &
                          percent.mt < 20)

## Add labels to metadata
md14_positive$timepoint <- "Day 14"
md14_positive$group <- "Early"
md14_positive$selection <- "mCherry+"

#### D35 ####
# Load mCherry+ cells (tumor and surrounding microenvironment cells) from lungs collected on day 30
md35_positive <- tenx_load_qc("/gpfs0/home2/gdrobertslab/lab/Counts/S0084/filtered_feature_bc_matrix",
                              species_pattern = "^mm10_")

## Add labels to metadata
md35_positive$timepoint <- "Day 35"
md35_positive$group <- "Late"
md35_positive$selection <- "mCherry+"

#Subset for QC
md35_positive <- subset(md35_positive,
                        subset = nCount_RNA > 800 &
                          nCount_RNA < 20000 &
                          percent.mt < 10)
```

## Load and Process Mouse and Human Cells Together

```{r all_load}
#### D14 ####
# Load mCherry+ cells (tumor and surrounding microenvironment cells) from lungs collected on day 14
d14_positive_all <- tenx_load_qc("/gpfs0/home2/gdrobertslab/lab/Counts/S0082/filtered_feature_bc_matrix",
                                 species_pattern = "^hg19_|^mm10")

# Subset for QC
d14_positive_all <- subset(d14_positive_all,
                           subset = nCount_RNA > 800 &
                             nCount_RNA < 10000 &
                             percent.mt < 20)

## Add labels to metadata
d14_positive_all$timepoint <- "Day 14"
d14_positive_all$group <- "Early"
d14_positive_all$selection <- "mCherry+"

#### D35 ####
# Load mCherry+ cells (tumor and surrounding microenvironment cells) from lungs collected on day 35
d35_positive_all <- tenx_load_qc("/gpfs0/home2/gdrobertslab/lab/Counts/S0084/filtered_feature_bc_matrix",
                                 species_pattern = "^hg19_|^mm10")

## Add labels to metadata
d35_positive_all$timepoint <- "Day 35"
d35_positive_all$group <- "Late"
d35_positive_all$selection <- "mCherry+"

#Subset for QC
d35_positive_all <- subset(d35_positive_all,
                           subset = nCount_RNA > 800 &
                             nCount_RNA < 40000 &
                             percent.mt < 20)

tumor_all <- merge(d14_positive_all, y = d35_positive_all,
                   add.cell.ids = c("d14", "d35"),
                   project = "Early vs Late OS Mets")

tumor_all <- NormalizeData(tumor_all) %>%
  ScaleData() %>%
  FindVariableFeatures()
tumor_all <- RunPCA(tumor_all, features = VariableFeatures(tumor_all)) %>%
  FindNeighbors(dims = 1:20) %>%
  FindClusters(resolution = 0.15) %>%
  RunUMAP(dims = 1:20)

# Save
save(tumor_all, file = "Data/early_late_tumor_allcelltypes.RData")

umap_all <- DimPlot(tumor_all,
                    reduction = "umap",
                    pt.size = 1,
                    label = T) +
  theme(aspect.ratio = 1)

pdf("Figures/early_late_umap_all.pdf",
    width = 5,
    height = 5)
umap_all
dev.off()

umap_timepoint_all <- DimPlot(tumor_all,
                              reduction = "umap",
                              pt.size = 1,
                              label = T,
                              split.by = "timepoint") +
  theme(aspect.ratio = 1)

pdf("Figures/early_late_umap_timepoint_all.pdf",
    width = 5,
    height = 5)
umap_timepoint_all
dev.off()
```

## Human Cell Only Processing

```{r human-processing}
# Human
tumor <- merge(d14_positive, y = d35_positive,
               add.cell.ids = c("d14", "d35"),
               project = "Early vs Late OS Mets")

tumor <- NormalizeData(tumor) %>%
  ScaleData() %>%
  FindVariableFeatures()
tumor <- RunPCA(tumor,
                features = VariableFeatures(tumor)) %>%
  FindNeighbors(dims = 1:20) %>%
  FindClusters(resolution = 0.15) %>%
  RunUMAP(dims = 1:20)

# Save
save(tumor, file = "Data/early_late_tumor.RData")
DimPlot(tumor,
        reduction = "umap",
        pt.size = 1,
        label = T) +
  theme(aspect.ratio = 1)

# Use timepoint naming (Day 14/Day 35) for UMAP plotting
umap_timepoint <- DimPlot(tumor,
                          reduction = "umap",
                          pt.size = 1,
                          group.by = "timepoint",
                          label = T) +
  theme(aspect.ratio = 1)
umap_timepoint

pdf("Figures/early_late_umap.pdf",
    width = 5,
    height = 5)
umap_timepoint
dev.off()

# Use basic naming (early/late) for UMAP plotting
umap_group <- DimPlot(tumor,
                      reduction = "umap",
                      pt.size = 1,
                      group.by = "group",
                      label = T) +
  theme(aspect.ratio = 1)
umap_group

pdf("Figures/early_late_umap.pdf",
    width = 5,
    height = 5)
umap_group
dev.off()
```

## Mouse Cell Only Processing

```{r mouse-processing}
# Mouse
microenv <- merge(md14_positive, y = md35_positive,
                  add.cell.ids = c("d14", "d35"),
                  project = "Early vs Late OS Mets")

microenv <- NormalizeData(microenv) %>%
  ScaleData() %>%
  FindVariableFeatures()
microenv <- RunPCA(microenv, features = VariableFeatures(microenv)) %>%
  FindNeighbors(dims = 1:20) %>%
  FindClusters(resolution = 0.15) %>%
  RunUMAP(dims = 1:20)

DimPlot(microenv,
        reduction = "umap",
        pt.size = 1, label = T) +
  coord_fixed()

DimPlot(microenv,
        reduction = "umap",
        pt.size = 1,
        label = T,
        split.by = "group") +
  coord_fixed()

save(microenv, file = "Data/early_late_microenv.RData")
```

```{r human_geneplots}
dot_plot <- DotPlot(tumor,
                    features = c("BCL2", 
                                 "BCL2L1",
                                 "BCL2L2",
                                 "MCL1"),
                    group.by = "group",
                    scale = F,
                    cols = "Spectral") +
  RotatedAxis()

pdf("Figures/dot_plot.pdf",
    width = 7,
    height = 4)
dot_plot +
  coord_fixed() 
dev.off()

vln_plot <- VlnPlot(tumor,
                    features = c("BCL2", 
                                 "BCL2L1",
                                 "BCL2L2",
                                 "MCL1"),
                    group.by = "group") +
  RotatedAxis()

pdf("Figures/vln_plot.pdf",
    width = 6,
    height = 5)
vln_plot 
dev.off()

feature_plot <- FeaturePlot(tumor,
                            features = c("BCL2", 
                                         "BCL2L1",
                                         "BCL2L2",
                                         "MCL1"),
                            split.by = "group",
                            order = T) +
  theme(aspect.ratio = 1)

pdf("Figures/feature_plot.pdf",
    width = 6,
    height = 12)
feature_plot 
dev.off()
```


```{r cc}
library(rrrSingleCellUtils)

# Calculate cell cycle phase
tumor_cc <- kill_cc(tumor,
                    cc_regress = "Y")

tumor_cc <- FindNeighbors(tumor_cc, dims = 1:20) %>%
  FindClusters(resolution = 0.15) %>%
  RunUMAP(dims = 1:20)

umap_cc <- DimPlot(tumor_cc,
                   reduction = "umap",
                   pt.size = 1,
                   label = T,
                   group.by = "timepoint") +
  theme(aspect.ratio = 1)
umap_cc

pdf("Figures/umap_cc_bytrtment.pdf",
    width = 5,
    height = 5)
umap_cc
dev.off()

save(tumor_cc, file = "Data/early_late_tumor_cc.RData")
```
