---
title: "Timecourse Analysis of Lung Lesions"
author: "Emily Franz"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    number_sections: false
    code_folding: hide
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
    tidy = TRUE,
    echo = TRUE,
    cache = TRUE,
    collapse = TRUE,
    tidy.opts = list(width.cutoff = 95),
    message = FALSE,
    warning = FALSE,
    cache.lazy = FALSE
)
```

```{r lib}
# Load packages
library(Seurat)
library(tidyverse)
library(rrrSingleCellUtils)

# Set random generator seed to facilitate reproducibility
set.seed(888)

# set working directory 
setwd("/gpfs0/home2/gdrobertslab/lab/Analysis/Emily/MCL1_early_met_survival/")
```

# Load

```{r load}
# Load list of all objects
load("output/rdata/sobj_list.rds")

# Merge mouse early and late datasets
pos_m <- merge(sobj_list[["d14_pos_m"]],
               y = c(sobj_list[["d21_pos_m"]],
                     sobj_list[["d28_pos_m"]],
                     sobj_list[["d35_pos_m"]],
                     sobj_list[["d49_pos_m"]]),
               add.cell.ids = c("d14",
                                "d21",
                                "d28",
                                "d35",
                                "d49"),
               project = "Timepoint Analysis of OS Mets")

# Normalize, scale, find variable features
pos_m <- NormalizeData(pos_m) %>%
  ScaleData() %>%
  FindVariableFeatures()

# PCA
pos_m <- RunPCA(pos_m,
                features = VariableFeatures(pos_m))
ElbowPlot(pos_m)

# Find neighbors, clusters, do umap
pos_m <- FindNeighbors(pos_m, dims = 1:14) %>%
  FindClusters(resolution = 0.2) %>%
  RunUMAP(dims = 1:14)

# Use basic naming (early/late) for UMAP plotting
umap_mgroup <- DimPlot(pos_m,
                      reduction = "umap",
                      pt.size = 1,
                      group.by = "timepoint",
                      label = T,
                      shuffle = T) +
  theme(aspect.ratio = 1)
umap_mgroup

pdf("Figures/timepoint_mouse_umap.pdf",
    width = 5,
    height = 5)
umap_mgroup
dev.off()

rm(sobj_list)
```

### Clustering Resolution {.tabset}

#### Res0.1
```{r umap, fig.height=5, fig.width=10}
pos_m <- FindClusters(pos_m, resolution = 0.1) %>%
  RunUMAP(dims = 1:14)

DimPlot(pos_m,
        reduction = "umap",
        split.by = "timepoint",
        pt.size = 1,
        label = T) +
  coord_fixed()
```

#### Res0.15
```{r umap15, fig.height=5, fig.width=10}
pos_m <- FindClusters(pos_m,
                      resolution = 0.15) %>%
  RunUMAP(dims = 1:14)

DimPlot(pos_m,
        reduction = "umap",
        split.by = "timepoint",
        pt.size = 1,
        label = T) +
  coord_fixed()
```

#### Res0.2
```{r umap2, fig.height=5, fig.width=10}
pos_m <- FindClusters(pos_m,
                      resolution = 0.2) %>%
  RunUMAP(dims = 1:14)

DimPlot(pos_m,
        reduction = "umap",
        split.by = "timepoint",
        pt.size = 1,
        label = T) +
  coord_fixed()
```

#### Res0.3
```{r umap3, fig.height=5, fig.width=10}
pos_m <- FindClusters(pos_m,
                      resolution = 0.3) %>%
  RunUMAP(dims = 1:14)

DimPlot(pos_m,
        reduction = "umap",
        split.by = "timepoint",
        pt.size = 1,
        label = T) +
  coord_fixed()
```

#### Res0.7
```{r umap7, fig.height=5, fig.width=10}
pos_m <- FindClusters(pos_m,
                      resolution = 0.7) %>%
  RunUMAP(dims = 1:14)

DimPlot(pos_m,
        reduction = "umap",
        split.by = "timepoint",
        pt.size = 1,
        label = T) +
  coord_fixed()
```

## Cell Type Assignment

```{r, dependson=c("load", "umap2")}
# Look at upregulated DEG to help determine cell id 
Idents(pos_m) <- pos_m$RNA_snn_res.0.3
markers <- FindAllMarkers(pos_m,
                          min.pct = 0.25,
                          logfc.threshold = 0.25,
                          only.pos = T)

#Hard to work with this function/datatable so this step removes genes not in the top 10 DEG for all clusters 
# Print top 10 in each cluster
markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> t

t <- as.data.frame(t)
t$cluster <- as.numeric(as.character(t$cluster))
t <- t[order(t$cluster),]
t <- t[,c(7, 1:6)]
t <- t[,c(7, 1:6)]
#could also use arrange() to sort by column

DT::datatable(t, 
              rownames = FALSE,
              extensions = c('FixedColumns',
                             'Buttons'),
              options = list(
                pageLength = 10,
                scrollX = TRUE,
                scrollCollapse = TRUE,
                dom = 'Bfrtip',
                buttons = c('copy',
                            'csv',
                            'excel')
              ))
```

### Singlr Cell Assignment

```{r singlr, dependson=c("load", "umap2")}
# Automatic prediction of cell types using SingleR
# BiocManager::install("SingleCellExperiment")
library(SingleR)
library(celldex)
library(SingleCellExperiment)

# Convert the Seurat object to a SCE object
pos_m_sce <- as.SingleCellExperiment(pos_m)

# Load the mouse reference library & immune-specific mouse data
ref1 <- celldex::MouseRNAseqData()
ref2 <- celldex::ImmGenData()

# Make cell type predictions using SingleR
pos_m_pred_types <- SingleR(test = pos_m_sce,
                            ref = list(ref1,
                                       ref2),
                            labels = list(ref1$label.main,
                                          ref2$label.main))

# Make cell type predictions using SingleR - FINE
pos_m_pred_types_fine <- SingleR(test = pos_m_sce,
                            ref = list(ref2),
                            labels = list(ref2$label.fine))
# Clean up environment
rm(pos_m_sce, ref1, ref2)
```

```{r singler_cont, dependson=c("load","umap2","singlr")}
# Transfer labels back to the Seurat object and plot
pos_m$singleR2 <- pos_m_pred_types$labels
pos_m$singleR2_fine <- pos_m_pred_types_fine$labels

maxv <- apply(pos_m_pred_types$scores, 
              MARGIN = 1, 
              function(x) max(x,
                              na.rm = TRUE))
hist(maxv,
     n = 200)

# Add scores of fine assignments to metadata
pos_m$singleRscore <- maxv  #scores may be a matrix

# Plot histograms
as.data.frame(pos_m@meta.data) %>%
  as_tibble() %>%
  ggplot(aes(x = singleRscore)) +
  geom_histogram(bins = 200) +
  facet_wrap(~singleR2,
             ncol = 3,
             scales = "free_y") #****

# Table of assignments per timepoint
table(pos_m$singleR2,
      pos_m$timepoint)

## FINE Cell Assignments
maxv_fine <- apply(pos_m_pred_types_fine$scores, 
                   MARGIN = 1, 
                   function(x) max(x,
                                   na.rm = TRUE))
hist(maxv_fine,
     n = 200)

# Add scores of fine assignments to metadata
pos_m$singleRscore_fine <- maxv_fine  #scores may be a matrix

# Plot histograms
as.data.frame(pos_m@meta.data) %>%
  as_tibble() %>%
  ggplot(aes(x = singleRscore_fine)) +
  geom_histogram(bins = 200) +
  facet_wrap(~singleR2_fine,
             ncol = 3,
             scales = "free_y") #****
```

```{r singlr_plot, dependson=c("load","umap2","singlr"), fig.width=12, fig.height=5}
# Plot singleR2 assignments on UMAP plot
Idents(pos_m) <- pos_m$singleR2
DimPlot(pos_m,
        reduction = "umap",
        pt.size = 0.5,
        label = T,
        repel = T,
        shuffle = T) +
  coord_fixed() +
  ggtitle("Mouse Reference")

# Rename cell ids
pos_m <- RenameIdents(pos_m,
                      "Dendritic cells" = "DC",
                      "Tgd" = "T cells",
                      "Granulocytes" = "Neutrophils",
                      "Hepatocytes" = "Epithelial cells",
                      "Cardiomyocytes" = "Fibroblasts",
                      "Neurons" = "Epithelial cells",
                      "Microglia" = "Macrophages",
                      "Stromal cells" = "Fibroblasts")

# Plot with new ids
DimPlot(pos_m,
        reduction = "umap",
        pt.size = 0.5,
        label = T,
        repel = T,
        shuffle = T) +
  coord_fixed() +
  ggtitle("Mouse Reference")

# Compare to clusters at res 0.3
Idents(pos_m) <- pos_m$RNA_snn_res.0.3
DimPlot(pos_m,
        reduction = "umap",
        pt.size = 0.5,
        label = T,
        repel = T,
        shuffle = T) +
  coord_fixed() +
  ggtitle("Resolution 0.3")

# Table of singlr assignments per cluster at resolution 0.3
table(pos_m$singleR2,
      pos_m$RNA_snn_res.0.3)
```

```{r singlr_fine_plot, dependson=c("load","umap2","singlr"), fig.width=50, fig.height=20}
# Plot singleR2 fine assignments on UMAP plot 
Idents(pos_m) <- pos_m$singleR2_fine
DimPlot(pos_m,
        reduction = "umap",
        pt.size = 0.5) +
  coord_fixed() +
  ggtitle("Mouse Reference - Fine Labels")

# Table of fine assignments per cluster at resolution 0.3
table(pos_m$singleR2_fine,
      pos_m$RNA_snn_res.0.3)
```

## Subset macrophage clusters for clearer distinctions

```{r}
# Subset clusters from res0.3 that have macrophage gene signatures
Idents(pos_m) <- pos_m$RNA_snn_res.0.3
macro <- subset(pos_m,
                idents = c(0,
                           1,
                           2,
                           3,
                           4,
                           7,
                           10,
                           16,
                           17))

macro <- FindNeighbors(macro, dims = 1:14) %>%
  FindClusters(resolution = 0.2) %>%
  RunUMAP(dims = 1:14)

DimPlot(macro,
        reduction = "umap",
        split.by = "timepoint",
        pt.size = 1,
        label = T) +
  coord_fixed()
```

```{r}
# Look at upregulated DEG to help determine cell id 
Idents(macro) <- macro$RNA_snn_res.0.2
markers <- FindAllMarkers(macro,
                          min.pct = 0.25,
                          logfc.threshold = 0.25,
                          only.pos = T)

#Hard to work with this function/datatable so this step removes genes not in the top 10 DEG for all clusters 
# Print top 10 in each cluster
markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> t

t <- as.data.frame(t)
t$cluster <- as.numeric(as.character(t$cluster))
t <- t[order(t$cluster),]
t <- t[,c(7, 1:6)]
t <- t[,c(7, 1:6)]
#could also use arrange() to sort by column

DT::datatable(t, 
              rownames = FALSE,
              extensions = c('FixedColumns',
                             'Buttons'),
              options = list(
                pageLength = 10,
                scrollX = TRUE,
                scrollCollapse = TRUE,
                dom = 'Bfrtip',
                buttons = c('copy',
                            'csv',
                            'excel')
              ))
```

```{r singlr_fine_plot-macro, dependson=c("load","umap2","singlr"), fig.width=50, fig.height=20}
# Plot singleR2 fine assignments on UMAP plot 
Idents(macro) <- macro$singleR2_fine
DimPlot(macro,
        reduction = "umap",
        pt.size = 0.5) +
  coord_fixed() +
  ggtitle("Mouse Reference - Fine Labels")

# Table of fine assignments per cluster at resolution 0.3
table(macro$singleR2_fine,
      macro$RNA_snn_res.0.3)
```


```{r}
sessionInfo()
```

